#!/bin/sh
# config maintainer script for gnukhata-core-engine
 
set -e

# source debconf stuff
. /usr/share/debconf/confmodule

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
   . /usr/share/dbconfig-common/dpkg/config.pgsql

   dbc_dbname="diaspora_production"
   dbc_dbuser="diaspora"

   dbc_go diaspora $@
fi

# What is your pod address?
db_input high diaspora/url || true
db_go

# Configure pod address.
db_get diaspora/url
if ! test -f /etc/diaspora.conf
	then 
		echo export SERVERNAME=$RET >> /etc/diaspora.conf
		sed -e "s/SERVERNAME_FIXME/$RET/" -e "s/DIASPORA_SSL_PATH_FIXME/\\/etc\\/diaspora/" -e "s/DIASPORA_ROOT_FIXME/\\/usr\\/share\\/diaspora/" /usr/share/doc/diaspora/nginx.conf.example >/etc/nginx/sites-available/$RET
		ln -s /etc/nginx/sites-available/$RET /etc/nginx/sites-enabled/
fi

if [ "$RET" = "false" ]; then
    db_go
fi

