#! /bin/sh
# postinst script for gnukhata-core-engine
# copied from postinst script for hplip
# $Id: hplip.postinst,v 1.1 2005/10/15 21:39:04 hmh Exp $
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.


case "$1" in
    configure)

	. /etc/diaspora/diaspora-common.conf
	cd ${diaspora_home}
#	echo "Installing gems with rubygems (their debian packages have bugs)..."
# These gems need more work before they can be apt-get
#	if ! gem list ^devise$ | grep devise
#		then gem install -v=3.4.1 devise
#	fi
	
	echo "Setting up environment varibales..."
	/usr/lib/diaspora-common/scripts/set-env-diaspora.sh
	echo RAILS_ENV=$RAILS_ENV DB=$DB ENVIRONMENT_URL=$ENVIRONMENT_URL
	
	echo "Verifying we have all required libraries..."
	sudo -u diaspora -E bundle install --local
	echo "Initializing database..."
	sudo -u diaspora -E bundle exec rake db:create db:schema:load
	echo "Precompiling assets..."
	sudo -u diaspora -E bundle exec rake assets:precompile
	sudo -u diaspora  touch public/source.tar.gz
	echo "Starting diaspora service..."
	sudo -u diaspora -E -i nohup ./script/server &
	echo "Copy $SERVERNAME-bundle.pem and $SERVERNAME.key to /etc/diaspora/ssl"
	echo "And reload nginx, run # /etc/init.d/nginx reload"
	echo "visit your pod at $ENVIRONMENT_URL"
	echo "To stop diaspora, run # killall -9 unicorn_rails foreman sidekiq"
	echo "To see the service status, run # /etc/init.d/diaspora status"
   ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
