#! /bin/sh
set -e

# Hardcore variables as diaspora-common.conf won't be available if both
# installed together
diaspora_home=/usr/share/diaspora

# Remove bin directory if upgrading from diaspora-installer
if test -d ${diaspora_home}/bin
then
    rm -rf ${diaspora_home}/bin
fi

case "$1" in
    upgrade)
        ;;
    abort-upgrade|install)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
