language: ruby
sudo: false
rvm:
  - 2.2.4
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/rails31.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails32.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails31.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails40.gemfile
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
